### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by mgingras** [wesbos/Sublime-JS-to-CoffeeScript#3]
It isn't that clear how to install the package in sublime from your documentation alone.

**Comment by dagifted1** [comment]
how's the ST3 version looking?

**Comment by kkortes** [comment]
Bumb here.

A common task when developing is converting JS to Coffee when you find some snipped on the internet that you wanna use. So having that in ST3 for instant access would be gold.

**Comment by TangMonk** [comment]
ST3, please

**Comment by nazartokar** [comment]
Guys, what about ST3 and Package?

**Comment by wesbos** [comment]
ST3 is now supported - thanks to @AfzalivE for this

**Comment by TangMonk** [comment]
cool!
